# Generated by Django 4.2.10 on 2024-02-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='instant',
            field=models.DateTimeField(null=True),
        ),
    ]
